version: '1.0'
services:
  vite_docker:
    image: node:alpine
    container_name: beacon_maps
    entrypoint: /bin/sh
    ports:
      - 80:80
    working_dir: /usr/src/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
